version: "3.8"

services:
  backend:
    build: .
    container_name: ml-api
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend