version: "3.8"

services:
  backend:
    build: .
    container_name: ml-api
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model

  nginx:
    image: nginx:latest
    container_name: nginx
    network_mode: "host"
    volumes:
      - C:/Users/alexu/Documents/Squareroots.ai/Belden/Deployment project new/frontend:/usr/share/nginx/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
